# This file could be used for testing the API with Visual Studio Code

## Retrieve all tickets
GET http://localhost:3001/api/tickets HTTP/1.1
###


## Retrieve all bllocks associated to a ticket
GET http://localhost:3001/api/blocks?id=ciao HTTP/1.1
###


## Create new ticket
PATCH http://localhost:3001/api/ticket HTTP/1.1
content-type: application/json

{
    "title": "Ticket from HTTP request",
    "text": "This is a ticket",
    "state": "closed",
    "owner": 3,
    "id": 1
}
###

## Create new block 
POST http://localhost:3001/api/blocks HTTP/1.1
content-type: application/json

{
    "text": "This is a ticket00",
    "ticketId": 5,
    "author": 5
}
###

## Login
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "user3",
    "password": "password3",
    "credentials": "include"
}
###


GET http://localhost:3001/api/sessions/current HTTP/1.1



## Patch ticket
POST http://localhost:3001/api/tickets HTTP/1.1
content-type: application/json

{
    "title": "Ticket from HTTP request",
    "text": "This is a ticket",
    "category": "payment",
    "state": "closed",
    "owner": 3
}
###
